spring:
    application:
        name: challenge
    graphql:
        graphiql.enabled: true
    cache:
        type: caffeine
        cache-names: peopleList,personDetail,filmsList,filmDetail,starshipsList,starshipDetail,vehiclesList,vehicleDetail
        caffeine:
            spec: maximumSize=1000,expireAfterWrite=10m
    datasource:
        url: jdbc:h2:mem:swapi;MODE=PostgreSQL
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
management:
    endpoints.web.exposure.include: health,info,metrics,caches
    endpoint.health.show-details: when_authorized

resilience4j:
    circuitbreaker:
        instances:
            swapi:
                sliding-window-size: 10
                failure-rate-threshold: 50
                wait-duration-in-open-state: 10s
    retry:
        instances:
            swapi:
                max-attempts: 3
                wait-duration: 250ms

swapi:
    base-url: https://www.swapi.tech/api

jwt:
    secret:  secret1359
    expiration-minutes: 60